export const NUM_SECTORS = 8;
export const MAX_IN_SECTOR = 10;
export const LOG_TYPES = ['dispense', 'take', 'refill'] as const;

export const MEDICINE_NAMES = [
	'Transonide',
	'Effivirase',
	'Solafenide',
	'Amrelin',
	'Lansoramine',
	'Tristone',
	'Advarix Parogine',
	'Estroracin Thalitacept',
	'Vitratoin Ageneset',
	'Preponel Hydrolin',
	'Bactrolise',
	'Agelinum',
	'Dextroprin',
	'Oxymorenone',
	'Abitorol',
	'Marnesin',
	'Anetora Phosfenac',
	'Aciprex Amphonosine',
	'Doctocept Robabrate',
	'Hyalutecan Glucoprox',
	'Alogderal',
	'Insurolac',
	'Flutaprox',
	'Empizumab',
	'Ampylac',
	'Olmeveset',
	'Zicorall Adrenamine',
	'Imisine Tamonoin',
	'Norbinol Alapentin',
	'Palodene Omnistin',
	'Alcanamic',
	'Somaferon',
	'Vibracetam',
	'Albuvirenz',
	'Serodafinil',
	'Immunamic',
	'Bextanyl Beclolimus',
	'Transpirin Acetanalin',
	'Synthemumab Cyprodine',
	'Ganitrisin Nedoferal',
	'Flexemectin',
	'Belatosine',
	'Aboboveset',
	'Primamumab',
	'Belavice',
	'Benazetorol',
	'Alfutora Fluadeine',
	'Tercocelex Estrazine',
	'Rivastadil Altazoxane',
	'Kinoxone Tretizine'
];
